# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using v and h
bind v split-window -h
bind h split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf

# Enable mouse mode
set -g mouse on

# start first window and pane at 1, not zero
set -g base-index 1
set -g pane-base-index 1

######################
### DESIGN CHANGES ###
######################

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none
